services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mylittlepassword
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--username", "$$MONGO_INITDB_ROOT_USERNAME", "--password", "$$MONGO_INITDB_ROOT_PASSWORD", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  nodejs-app:
    build:
      context: .
    ports:
      - "3000:3000" 
    depends_on:
      - mongodb
    volumes:
      - .:/app
    # environment:
    #   - NODE_ENV=production
    # volumes:
    #   - .:/app

volumes:
  mongodata: